### PR TITLE
Add PR naming guidelines

### PR DESCRIPTION
**Pull request by dcalhoun**
We currently have Pull Request titles like... 
- `Feature/did something`
- `Bug/add fix for this`
- `WIP throw away branch`
- `a lower case sentence is great`
- `i am really fond of punctuation!!`

I'd like to propose that our PR's should follow the same format as our commit messages (e.g. – capitalized, imperative mood, no period, etc).

P.S. – One great feature of GitHub PR's is that if your PR has a single commit (i.e. – you rebase and squash your commits), then GitHub will auto-populate the title/body with your commit title/body. This is another reason why I like/recommend squashing branches into a single commit.

### CODE REVIEW

**Comment by traviskroberts** [comment]
So, our branch names would look like this?

- `bug/fix-parent-email-validation`
- `feature/allow-multiple-explore-modules`
- etc

**Comment by traviskroberts** [comment]
:+1:

**Comment by traviskroberts** [comment]
@stevencwarren @natetallman @DylanAndrews Can you guys sign off on this as well?

**Comment by stevencwarren** [comment]
:+1:

**Pull request merged**
